config/routes.rb
Rails.application.routes.draw do

  resources :about, only: [:index]

  get 'static_pages/help'
  get 'static_pages/faq'
  get 'static_pages/about'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

  get '/login' => 'session#new'
    post '/login' => 'session#create'
    get '/logout' => 'session#destroy'

    get '/signup' => 'user#new'
    post '/users' => 'user#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 5 }
  validates :password_confirmation, presence: true, length: { minimum: 5 }

  def self.authenticate_with_credentials(email, password)
    @user = User.find_by_email(email.strip.downcase).try(:authenticate, password)
    if @user
      @user
    else
      nil
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

  def index
    @Category = Category.order(id: :desc).all
  end

  def new
    @Category = Category.new
  end

  def create
    @Category = Category.new(Category_params)

    if @Category.save
      redirect_to [:admin, :Category], notice: 'Category created!'
    else
      render :new
    end
  end



  private

  def Category_params
    params.require(:Category).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @product_count =  Product.sum(:quantity)
    @category_count = Category.count 
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

  def add_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, +1)

    redirect_back fallback_location: root_path
  end

  def remove_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, -1)

    redirect_back fallback_location: root_path
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_subtotal_cents,
      description: "Khurram Virani's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end
    order.save!
    order
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && User.authenticate_with_credentials(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end


  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/about/index.html.erb
<h1>Welcome to About Us Page....</h1>

app/views/admin/categories/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Categories</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Category', [:new, :admin, :category], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Types of Items</th>
        </tr>
      </thead>
      <tbody>
        <%= render @Category %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/categories/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="well">
    <%= link_to 'All Categories', [:admin, :categories], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @Category] do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>



        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/dashboard/show.html.erb
<h3>Inventory Details</h3>
<div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Total Quantity</th>
          <th>Total Category Available</th>
        </tr>
      </thead>
      <tr>
      <td><%= @product_count %></td>
      <td><%= @category_count %></td>
      </tr>

      </table>
      </div>

      <%= link_to 'Products', admin_products_path, class: "btn btn-success" %>

app/views/admin/products/_product.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= product.category.name %>
  </td>
  <td>
    <%= product.price %>
  </td>
  <td>
    <%= product.quantity %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, product], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/products/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Products</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Qty Remaining</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/products/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Product</h1>
  </header>

  <div class="well">
    <%= link_to 'All Products', [:admin, :products], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @product] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.select :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name), { include_blank: true }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :quantity %>
          <%= form.number_field :quantity, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price, class: 'form-control' %>
        </div>



        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image %>
        </div>

        <%= form.submit 'Create Product', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/carts/_item.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    $<%= product.price %>
  </td>
  <td>
    <div>
    <%= button_to remove_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-danger' do %> - <% end %>
    <%= quantity %>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-success' do %> + <% end %>
    </div>
  </td>
  <td>
    $<%= product.price * quantity %>
  </td>
</tr>

app/views/carts/show.html.erb
<section class="cart-show">

  <% if enhanced_cart.length == 0 %>
    <h3 class="alert alert-danger">There is no item in cart</h3>
    <%= link_to 'Go Back', :root %>
  <% else %>

  <header class="page-header">
    <h1>My Cart</h1>
  </header>

  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% enhanced_cart.each do |item| %>
          <%= render 'item', product: item[:product], quantity: item[:quantity].to_i %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            $<%= cart_subtotal_cents / 100.0 %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= cart_subtotal_cents %>"
          data-name="Jungle"
          data-description="Khurram Virani's Jungle Order"
          data-locale="auto"
          data-email="kvirani@gmail.com"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>

  <% end %>

</section>

app/views/categories/_category.html.erb
<tr>
  <td> <%= category.name  %></td>
<tr>

app/views/categories/show.html.erb
<section class="categories-show">

  <header class="page-header">
    <h1>
      <%= @category.name %>
      <small>(<%= pluralize @products.size, 'product' %>)</small>
    </h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/layouts/_top_nav.html.erb
<header class="<%= current_page?(root_path) ? "hero" : "hero small" %>">
  <section class="title">
    <h3>Welcome to</h3>
    <h1>The Jungle</h1>
    <h2>Where you can find any plants!</h2>
  </section>
</header>
<nav class="navbar navbar-expand-lg navbar-dark sticky-nav">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Jungle</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          > %>
          <li>
          <%= link_to 'About', about_index_path %>
        </li>
            <%# Categories %>
          <%# </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown"> %>
            <% Category.all.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, category, class: "nav-link" %>
            </li>
            <% end %>
          <%# </ul>
        </li> %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle text-danger"
            href="#"
            id="navbarDropdownAdmin"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Admin
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li><%= link_to 'Dashboard', [:admin, :root], class: "nav-link" %></li>
            <li><%= link_to 'Products', [:admin, :products], class: "nav-link" %></li>
            <li><%= link_to 'Category',  [:admin, :categories] %></li>
          </ul>
        </li>
        <% if current_user %>
         <l1> Signed in as <%= current_user.name %></li> <li> <%= link_to "Logout", '/logout' %></li>
          <% else %>
        <li>  <%= link_to 'Login', '/login' %> </li>  <li> <%= link_to 'Signup', '/signup' %></li>
        <% end %>
        <li class="nav-item end-0">
          <%= link_to cart_path, class: "nav-link " do %> <%= fa_icon "shopping-cart" %>
          My Cart (<%= cart.size %>) <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<script>
(function(){
const gnr = () => {
    const uptitle = document.querySelector("section.title h3");
    const subtitle = document.querySelector("section.title h2");
    const header = document.querySelector("header.hero");

    uptitle.style.fontSize = "5em";
    uptitle.style.fontWeight = 900;
    uptitle.style.textAlign = "center";

    subtitle.innerHTML =
      "<p>Watch it bring you to your</p><p> shu-n-n-n-n-n-n-n-n knees, knees!</p>";
  };
  const title = document.querySelector("header.hero");
  title.addEventListener("dblclick", gnr);
  
})()
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;0,700;0,800;0,900;1,600;1,700;1,800;1,900&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top_nav' %>

  <main class="container">
    <%= yield %>
  </main>

  <%= yield :end_of_body %>

  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQ</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Help</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2021 Jungle, Inc</p>
  </footer>
</body>
</html>

app/views/products/_product.html.erb
<article>
  <%= link_to product_path(product) do %>
    <%= image_tag product.image.thumb.url , alt: product.name %>
    <h1>
      <span><%= product.name %></span>
      <span><%= humanized_money_with_symbol product.price %></span>
    </h1>
  <% end%>
  <% if product.quantity == 0 %>
  <aside class="soldout">
    <span>SOLD OUT!</span>
  </aside>
  <% end %>
  <div>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn' ,
    method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %> 
    <% end %>
  </div>
</article>

app/views/products/index.html.erb
<section class="products-index">
  <header class="page-header">
    <div class="intro">
      <p>
        Looking for a way to add some life to your home? Look no further than our online plant shop! We have a wide variety of beautiful plants and flowers, as well as all the accessories you need to keep them healthy and happy. Plus, our prices are unbeatable! So what are you waiting for?
      </p>
      <p>
        At our online plant shop, we only sell the highest quality plants and flowers. We source our products from reputable growers and nurseries, so you can be sure you're getting a healthy, beautiful plant. Plus, ordering is quick and easy! We offer free shipping on all orders over $50, so it's easy to get the plants you want without breaking the bank.
      </p>
      <p>
        We have a wide variety of plants and flowers available for purchase on our website. Whether you're looking for something small and delicate or big and bold, we have the perfect plant for you. We also carry a selection of accessories, including potting soil, pots and containers, watering cans, and more.
      </p>
    </div>
  </header>

  <div class="products">
    <%= render @products %>
  </div>
</section>

app/views/products/show.html.erb
<section class="products-show">
  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">
    <%= image_tag @product.image.url, class: 'main-img' %>
    <div>
      <h1><%= @product.name %></h1>
      <p><%= @product.description %></p>
      <div class="quantity">
        <span><%= @product.quantity %> in stock at </span>
        <span>$<%= @product.price %></span>
      </div>
      <div class="price">          
        <%= button_to add_item_cart_path(product_id: @product.id), class: 'btn' , method: :post do %>
          <%= fa_icon "shopping-cart", text: 'Add' %>
        <% end %>          
      </div>
    </div>
  </article>

</section>

app/views/session/new.html.erb
<h1>Login</h1>

<%= form_tag '/login' do %>

  Email: <%= text_field_tag :email %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/user/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
<% end %>